# Generated by Django 4.2.7 on 2023-11-01 17:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("LibraryApi", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="category",
            field=models.CharField(default="Uncategorized", max_length=255),
        ),
    ]
