# Generated by Django 4.2.7 on 2023-11-05 22:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("LibraryApi", "0003_category_alter_book_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="cover_image",
            field=models.ImageField(blank=True, null=True, upload_to="books/covers/"),
        ),
    ]
