# Generated by Django 4.2.7 on 2024-03-09 00:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('LibraryApi', '0005_alter_booking_user_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='added_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='book',
            name='book_code',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='dewey_decimal_category_range',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='dewey_decimal_number',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='page_number',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='published_place',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
