# Generated by Django 4.2.7 on 2024-03-09 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LibraryApi', '0007_book_updated_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_code',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='page_number',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='updated_by',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
